version: '3'
services:
  meu-app-invoice-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoice-generator-microservice
    image: invoice-generator:1.0.0
    ports:
      - "5002:5002"
    volumes:
      - ./database/database-file:/app/database/database-file
      - ./invoices:/app/invoices
      - ./log/logs-files:/app/log/logs-files
    environment:
      - API_TITLE=Invoice Generator
      - VERSION=1.0.0
      - SECRET_KEY=Advanced Backend Development
      - PORT=5002
      - HOST=0.0.0.0
      - TZ=America/Sao_Paulo
    networks:
      - puc-microservice

networks:
  puc-microservice:
    external: true
